[project]
name = "energy_forecast"
description = "energy_forecast python package"
readme = "README.md"
requires_python = ">=3.9.13"
# version = "0.1.0"
dynamic = ["version"]
license = "MIT"
authors = [
    { name = "Azam Din", email = "adin786@gmail.com" }
]
dependencies = [
    "pandas",
    "matplotlib",
]

[project.optional-dependencies]
dev = ["black"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"